<?php



/**
 * Skeleton subclass for representing a row from the 'sf_guard_user_address' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * mar. 24 janv. 2012 17:23:48 CET
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfPlopGuardPlugin.lib.model
 */
class sfGuardUserAddress extends BasesfGuardUserAddress {

	public function __toString()
	{
		return $this->getAddressName();
	}

} // sfGuardUserAddress
