<?php



/**
 * Skeleton subclass for representing a row from the 'sf_guard_user_profile' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Mon Mar 28 17:12:23 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfGuardProfilePlugin.lib.model
 */
class sfGuardUserProfile extends BasesfGuardUserProfile {

  /**
   * Returns a combination of the column first_name, last_name and role
   * @return String
   */
  public function getNameWithRole()
  {
    if ($this->getRole())
      return $this->getFullName() . ' - ' . $this->getRole();
    else
      return $this->getFullName();
  }

  /**
   * Returns a combination of the column first_name, last_name and role
   * @return String
   */
  public function getFullName()
  {
    if ($this->getFirstName() || $this->getLastName())
      return $this->getFirstName()
        . ' '
        . $this->getLastName()
      ;
    else
      return $this->getsfGuardUser()->getUsername();
  }

  /**
   * Shortcut function to get the public status of the user profile.
   * @return Boolean
   */
  public function isPublic()
  {
    return $this->getIsPublic();
  }
  
  public function getAddress()
  {
    $addresses = $this->getsfGuardUser()->getsfGuardUserAddresss();
    if (count($addresses) > 0)
      return $addresses[0];
  }

} // sfGuardUserProfile
