<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.0-dev on:
 *
 * Mon Mar 28 17:12:23 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfGuardProfilePlugin.lib.model
 */
class sfGuardUserProfilePeer extends BasesfGuardUserProfilePeer {

} // sfGuardUserProfilePeer
